### ISSUE TITLE
Wrong path to src-directory for BtachJobs-Sources

### ISSUE THREAD

**Issue by danielhorn** [berndbischl/parallelMap#16]
It seems like the src-directory (e.g. parallelMap_BatchJobs_srcs_1226f6e0cd0) is created in the working directory, not in the storagedir. See this code and watch your directories:

library(parallelMap)
f = function() runif(8e8)
parallelStart(mode = "BatchJobs", storagedir = "tst")
parallelExport("f")
z = parallelMap(function(i) {f(); 1},
  i = 1:2, impute.error = NA)
parallelStop()

**Comment by berndbischl** [comment]
This was fixed a longer time ago
