### ISSUE TITLE
`parallelMap` does not work with unregistered levels

### ISSUE THREAD

**Issue by larskotthoff** [berndbischl/parallelMap#27]
I cannot specify a parallellisation level in `parallelMap` anymore without also explicitly specifying it when starting the backend. I get an error message telling me that the level is not registered.

Background: I'm using `paralleMap` in [LLAMA](https://bitbucket.org/lkotthoff/llama)'s model building functions and specify a level so that the parallelisation can be turned on and off. This used to work, but now I get an error message when running the code without a parallel backend.

The commit that introduced the check that breaks things is 587cf026d692b128bea6bbe6ca82e9386a086d31. Is this a deliberate interface change, and if so, how should I specify parallelisation levels now?

**Comment by berndbischl** [comment]
Improved docs adn README, also we warn now in parallelStart if level is not found
