### ISSUE TITLE
parallelStart(mode = ) has no option for batchtools

### ISSUE THREAD

**Issue by smilesun** [berndbischl/parallelMap#48]
If I want to reduce a large registry , I want to use parallelMap, but parallelStart only has mode = "batchjobs" which will corrupt a lot of functions in batchtools. 

 parallelStart(mode = "BatchJobs", resources = list(walltime = 3600)) ---------------------------------------------------------------------------------------------
  parallelExport("getFront", "reg") # make sure the slave process could use the variables being exported
  parallelLibrary("mlr", "batchtools", "ParamHelpers", "emoa", "smoof", "OpenML")
  parallelSource("experiments/experiments_global_defs.R")

So this will mask all functions in batchtools to batchjob functions

**Comment by berndbischl** [comment]
parallelStartBatchtools  should work from the master branch now, for you, as initial function call.

for parallelStart I need to check whether this is simply a documentation issue, in any case the fix should be trivial.

please tell me whether bt with pm works for you if you use parallelStartBatchtools now

**Comment by smilesun** [comment]
Yes, it works quite well if one use
`parallelStartBatchtools(resources = list(walltime = 3600))
`

**Comment by berndbischl** [comment]
bug the bug for parallelStart still exists, so lets keep this open

**Comment by jakob-r** [comment]
I think everything is fine and the following works:
```r
library(parallelMap)
parallelStart(mode = "batchtools", bt.resources = list(walltime = 3600))
```

PS: @smilesun You have to call `parallelStart(mode = "BatchJobs", bj.resources = list(...))` or `parallelStart(mode = "batchtools", bt.resources = list(walltime = 3600))`.

**Comment by jakob-r** [comment]
ping @berndbischl @smilesun

**Comment by berndbischl** [comment]
should be ok now

**Comment by vjcitn** [comment]
Would you update the man page (and any more prominent documents) to reflect the capacity to use mode = "batchtools"?

**Comment by nick-youngblut** [comment]
Is batchtools even supported in the latest CRAN release? I don't see it anywhere in the CRAN docs.

**Comment by jakob-r** [comment]
It's only supported on the gh release yet

**Comment by nick-youngblut** [comment]
Thanks @jakob-r for letting me know. Sorry for posting on a closed issue. Once `parallelmap` is updated on CRAN, I'll update the [conda-forge parallelmap feedstock](https://github.com/conda-forge/r-parallelmap-feedstock).

**Comment by berndbischl** [comment]
@nick-youngblut *i* have to sorry for not being faster on this.
@jakob-r will you take this over?

**Comment by jakob-r** [comment]
If you want I can maintain parallelMap too. Is that what you meant?
