### ISSUE TITLE
Problem with parallelStartSocket(cpus=...): It doesn't work

### ISSUE THREAD

**Issue by mareichhoff** [berndbischl/parallelMap#54]
Hello,

Since some package updates (don't remember which ones), I can't use parallelMap. When I call parallelStartSocket(cpus=3L) the system runs and runs and runs... like in an endless loop. I have to break then. Do you know why this may happen? I give you my input and the sessionInfo. I tried it with the CRAN version 1.3, but also with the 1.4 github version. In both cases it's the same. Before I installed the updates yesterday the package worked properly.

```
R> library(parallelMap)
R> parallelStartSocket(cpus=3L)
Starting parallelization in mode=socket with cpus=3.

R> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] parallelMap_1.4

loaded via a namespace (and not attached):
[1] compiler_3.4.1  backports_1.1.0 parallel_3.4.1  tools_3.4.1     BBmisc_1.11     checkmate_1.8.3
```

**Comment by jakob-r** [comment]
Even something simple like 
```r
library(parallelMap)
parallelStartSocket(cpus=3L)
parallelMap(function(x) {x+1}, x = 1:10)
```
will fail?

**Comment by berndbischl** [comment]
in which call does your session "block"?
really with parallelStartSocket?
or with a call to parallelMap?

**Comment by mareichhoff** [comment]
It blocks after parallelStartSocket(cpus=...). So I can't calculate anything afterwards.
"library(parallelMap)" was o.k.
When I click on "Stop" in RStudio or ESC in R, it stops and the R prompt appears.

**Comment by berndbischl** [comment]
thats very weird - but without further info it will be nearly impossible to help here.

that function simple calls

```
library(parallel)
makePSOCKCluster(4) # or other number of cores
```


does that block too on your PC? if so, this is a problem with your "parallel" package installation

**Comment by mareichhoff** [comment]
```
R> library(parallel)
R> makePSOCKCluster(2)
Error in makePSOCKCluster(2) : could not find function "makePSOCKCluster"
R> traceback()
Kein traceback vefügbar 
```

**Comment by berndbischl** [comment]
makePSOCKcluster

PS: pls check with command completion / google yourself

**Comment by mareichhoff** [comment]
Yes, I saw it. There is the same thing. It's blocked after writing makePSOCKcluster...
Then it's the package parallel.... o.k. thank you. But strange.
Is version 3.4.1 the version you are using, too?

**Comment by berndbischl** [comment]
yup, same version here (but probably very different laptop / system)

hard to tell what is wrong on your system from here ... sorry :(

**Comment by mareichhoff** [comment]
Bernd, I know now why it didn't work, but I don't know why this happened. I just write it here, perhaps it may be important for you to know:

In my .Rprofile function I use the function .First and inside of this function I call "update.packages(ask=FALSE)". When I comment it out parallelStartSocket(...) works again fine. I don't know why, but I erased the line in .First now. Now everything works fine again. Thank you!
