### ISSUE TITLE
Is it possible to parallelize multiple levels? For example mlr.tuneParams and mlr.benchmark

### ISSUE THREAD

**Issue by lucasxteixeira** [berndbischl/parallelMap#69]
Hi,

I'm running a mlr benchmark with multiple learners (around 15 different learners) with nested resampling using the irace tuning control.
My question is: is it possible to run two parallelization levels on parallelMap?

If I use the mlr.benchmark level, the faster learners end firsts and only the more computational demanding learners remain running, a single thread for each. So end up with 4 maybe 5 threads running.

If I use the mlr.tuneParams level, the irace tuning control spawns 6 threads evaluates all of them and then after all of them finish, it creates 6 others. I know that this method is sequential in nature.

My point is either way the CPU cores are not fully used.
For example if a CPU has 12 cores I could run two learners at same time with each learner using 6 cores for tuning.

Right now I'm doing this manually: I create multiple R sessions and run them separately.

Thanks!

**Comment by pat-s** [comment]
Hi @lucasxteixeira, please do not [cross-post](https://stackoverflow.com/questions/56762713/in-mlr-and-parallelmap-it-possible-to-parallelize-multiple-levels-for-example-m).

**Comment by berndbischl** [comment]
No, currently this is not possible. 

Some comments:

a) You can achieve what you want by using batchtools. Write the benchmark itself in batchtools, (or have a look at ?batchmark, but I think I would rather write the code myself), then parallelize the resampling or tuning through parallelMap. This is what I do in my (larger) experiments on clusters and multiple machines.

b) In mlr3 many of these problems will go away as we are using the "futures" packages. And there will be no parallelization levels anymore.

@mllg
