### ISSUE TITLE
Error in custom measure parsing external function while using parallelization in mlr

### ISSUE THREAD

**Issue by AleBitetto** [berndbischl/parallelMap#73]
Hi,

can you please help me with the issue described here:
https://stackoverflow.com/questions/58149481/error-in-custom-measure-parsing-external-function-while-using-parallelization

I'm trying to use custom measure in `mlr` package using external function. If I run it without parallelization everything works. If I start the parallel mode it doesn't. Maybe you can check if the alternative way I explained in the end can be used in a proper way.

Thanks a lot

**Comment by pat-s** [comment]
Answered on [SO](https://stackoverflow.com/a/58285851/4185785).

Please do not cross-post. You opened the same issue three (!) times..
Unless you can verify that it is a bug, usage questions should go to SO.
